"""Common AI / resume-cliché phrases to detect and avoid.

Profession-agnostic. Used by GrammarValidator, StyleValidator, and the
deterministic polish pass.
"""

from __future__ import annotations

# Phrases that almost always mark AI or generic résumé filler.
AI_CLICHE_PHRASES: tuple[str, ...] = (
    "results-driven",
    "results driven",
    "highly motivated",
    "passionate about",
    "proven track record",
    "seasoned professional",
    "dedicated professional",
    "dynamic professional",
    "experienced professional",
    "professional with experience",
    "professional with knowledge",
    "professional with a strong",
    "professional with hands-on",
    "strong understanding of",
    "strong understanding",
    "in-depth knowledge of",
    "extensive experience in",
    "knowledge of",
    "leveraged my skills",
    "utilized my expertise",
    "spearheaded initiatives",
    "synergistic",
    "synergy",
    "cutting-edge",
    "cutting edge",
    "state-of-the-art",
    "state of the art",
    "best-in-class",
    "best in class",
    "world-class",
    "world class",
    "thought leader",
    "go-getter",
    "self-starter with",
    "detail-oriented professional",
    "team player with",
    "fast-paced environment",
    "fast-paced environments",
    "hit the ground running",
    "raise the bar",
    "move the needle",
    "at the end of the day",
    "in today's competitive",
    "as an ai",
    "as a language model",
    "i hope this helps",
    "certainly!",
    "absolutely!",
    "delve into",
    "delved into",
    "harness the power",
    "unlock the potential",
    "elevate the",
    "drive meaningful impact",
    "deliver exceptional results",
    "delivering exceptional results",
    "exceptional results",
    "foster collaboration",
    "cross-functional excellence",
    "end-to-end solutions",
    "holistic approach",
    "robust solution",
    "seamless integration across",
    "empower stakeholders",
    "optimize for success",
    "extensive experience in",
    "extensive experience",
    "dedicated professional",
    "compassionate healthcare professional",
    "organized administrative professional",
    "applies these skills across",
    "delivery-focused projects",
)

# Soft openings that become robotic when overused as bullet starts.
WEAK_BULLET_OPENINGS: tuple[str, ...] = (
    "responsible for",
    "worked on",
    "helped with",
    "assisted with",
    "tasked with",
    "duties included",
    "involved in",
    "knowledge of",
    "familiar with",
    "participated in",
)

# Transitions that often sound machine-generated in summaries.
UNNATURAL_TRANSITIONS: tuple[str, ...] = (
    "furthermore,",
    "moreover,",
    "additionally,",
    "in addition,",
    "subsequently,",
    "consequently,",
    "it is worth noting",
    "in conclusion,",
    "to summarize,",
    "overall,",
)
