"""CV upload API + Postgres-safe schema regression tests."""

from __future__ import annotations

import api_server
import auth
import cv_service
import db
from conftest import auth_header_for, register_test_user
from fastapi.testclient import TestClient


def _isolate_upload(monkeypatch, db_path, cvs_dir):
    monkeypatch.setattr(db, "REGISTRY_DB_PATH", db_path)
    monkeypatch.setattr(api_server.db, "REGISTRY_DB_PATH", db_path)
    monkeypatch.setattr(api_server.db, "ensure_multi_cv_storage", lambda: None)
    monkeypatch.setattr(cv_service.db, "REGISTRY_DB_PATH", db_path)
    # upload stores files under CVS_DIR via config
    import config as cfg

    monkeypatch.setattr(cfg, "CVS_DIR", cvs_dir)
    monkeypatch.setattr(db, "cv_db_path", lambda cv_id: cvs_dir / cv_id / "jobs.db")


def test_pg_tailor_versions_ddl_has_no_autoincrement(monkeypatch):
    """Regression: upload on Postgres failed with AUTOINCREMENT syntax error."""
    monkeypatch.setattr(db, "uses_postgres", lambda: True)
    ddl = db._cv_tailor_versions_ddl()
    assert "AUTOINCREMENT" not in ddl.upper()
    assert "GENERATED BY DEFAULT AS IDENTITY" in ddl.upper()


def test_sqlite_tailor_versions_ddl_keeps_autoincrement(monkeypatch):
    monkeypatch.setattr(db, "uses_postgres", lambda: False)
    ddl = db._cv_tailor_versions_ddl()
    assert "AUTOINCREMENT" in ddl.upper()


def test_pg_full_schema_includes_cv_tailor_versions():
    assert "cv_tailor_versions" in db._PG_FULL_SCHEMA
    assert "AUTOINCREMENT" not in db._PG_FULL_SCHEMA.upper()


def test_apply_cv_match_migrations_creates_tailor_table(db_path):
    with db.get_connection(db_path) as conn:
        db._apply_cv_match_migrations(conn)
        tables = db._table_names(conn)
    assert "cv_tailor_versions" in tables


def test_upload_cv_service_creates_jobs_schema(db_path, cvs_dir, monkeypatch):
    monkeypatch.setattr(db, "REGISTRY_DB_PATH", db_path)
    import config as cfg

    monkeypatch.setattr(cfg, "CVS_DIR", cvs_dir)
    monkeypatch.setattr(db, "cv_db_path", lambda cv_id: cvs_dir / cv_id / "jobs.db")

    cv = cv_service.upload_cv("CV.pdf", b"%PDF-1.4 fake-resume", db_path=db_path)
    assert cv["file_name"] == "CV.pdf"
    assert cv["file_ext"] == ".pdf"
    jobs_db = cvs_dir / cv["id"] / "jobs.db"
    assert jobs_db.exists()
    with db.get_connection(jobs_db) as conn:
        assert "cv_tailor_versions" in db._table_names(conn)


def test_api_upload_cv_pdf_succeeds(db_path, cvs_dir, monkeypatch):
    _isolate_upload(monkeypatch, db_path, cvs_dir)
    user = register_test_user(email="uploader@example.com", db_path=db_path)
    client = TestClient(api_server.app)
    res = client.post(
        "/cvs/upload",
        headers=auth_header_for(user),
        files={"file": ("CV.pdf", b"%PDF-1.4 hello", "application/pdf")},
    )
    assert res.status_code == 200, res.text
    body = res.json()["cv"]
    assert body["file_name"] == "CV.pdf"
    assert body["id"]


def test_api_upload_rejects_empty_file(db_path, cvs_dir, monkeypatch):
    _isolate_upload(monkeypatch, db_path, cvs_dir)
    user = register_test_user(email="empty@example.com", db_path=db_path)
    client = TestClient(api_server.app)
    res = client.post(
        "/cvs/upload",
        headers=auth_header_for(user),
        files={"file": ("CV.pdf", b"", "application/pdf")},
    )
    assert res.status_code == 400


def test_api_upload_rejects_unsupported_extension(db_path, cvs_dir, monkeypatch):
    _isolate_upload(monkeypatch, db_path, cvs_dir)
    user = register_test_user(email="badext@example.com", db_path=db_path)
    client = TestClient(api_server.app)
    res = client.post(
        "/cvs/upload",
        headers=auth_header_for(user),
        files={"file": ("notes.exe", b"MZ", "application/octet-stream")},
    )
    assert res.status_code == 400


def test_api_upload_requires_auth(db_path, monkeypatch):
    monkeypatch.setattr(api_server.db, "ensure_multi_cv_storage", lambda: None)
    client = TestClient(api_server.app)
    res = client.post(
        "/cvs/upload",
        files={"file": ("CV.pdf", b"%PDF", "application/pdf")},
    )
    assert res.status_code == 401


def test_api_upload_duplicate_returns_409(db_path, cvs_dir, monkeypatch):
    _isolate_upload(monkeypatch, db_path, cvs_dir)
    user = register_test_user(email="dup@example.com", db_path=db_path)
    client = TestClient(api_server.app)
    payload = {"file": ("CV.pdf", b"%PDF-same-bytes", "application/pdf")}
    first = client.post("/cvs/upload", headers=auth_header_for(user), files=payload)
    assert first.status_code == 200, first.text
    second = client.post(
        "/cvs/upload",
        headers=auth_header_for(user),
        files={"file": ("CV-copy.pdf", b"%PDF-same-bytes", "application/pdf")},
    )
    assert second.status_code == 409


def test_create_cv_runs_full_init_db_without_autoincrement_when_pg(monkeypatch, tmp_path, cvs_dir):
    """Simulate Postgres mode: DDL must not use AUTOINCREMENT during create_cv."""
    executed: list[str] = []

    class _FakeConn:
        def execute(self, sql, params=None):
            executed.append(sql if isinstance(sql, str) else str(sql))
            return type("C", (), {"fetchall": lambda self: [], "fetchone": lambda self: None, "rowcount": 0})()

        def executescript(self, script):
            executed.append(script)

        def commit(self):
            pass

        def rollback(self):
            pass

    class _Ctx:
        def __enter__(self):
            return _FakeConn()

        def __exit__(self, *a):
            return False

    monkeypatch.setattr(db, "uses_postgres", lambda: True)
    monkeypatch.setattr(db, "get_connection", lambda *a, **k: _Ctx())
    monkeypatch.setattr(db, "REGISTRY_DB_PATH", tmp_path / "registry.db")
    monkeypatch.setattr(db, "ensure_auth_schema", lambda *a, **k: None)
    monkeypatch.setattr(db, "init_registry_db", lambda *a, **k: None)
    # Still need get_user etc. skipped — just call migration helper
    with db.get_connection(tmp_path / "x") as conn:
        db._apply_cv_match_migrations(conn)

    joined = "\n".join(executed).upper()
    assert "CV_TAILOR_VERSIONS" in joined
    assert "AUTOINCREMENT" not in joined
    assert "GENERATED BY DEFAULT AS IDENTITY" in joined
